name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      run: echo "Configurar entorno"

    - name: Build
      run: echo "Build del proyecto"

    - name: Test
      run: echo "Ejecutar pruebas"
